syntax = "proto3";

option go_package = "./pb";

enum Operation {
    SET = 0;
    GET = 1;
    DELETE = 2;
}

message Txn {
    Operation operation = 1;
    string key = 2;
    bytes value = 3;
}

message Order {
    int64 timestamp = 1;
    repeated Txn txnList = 2;
}

message RecieptItem{
    int64 timestamp = 1;
    Operation operation = 2;
    bool status = 3;
    optional bytes val = 4;
}

message Reciept { 
    repeated RecieptItem items = 2;
}

message msg {
    
    bytes uuid = 1;
    bytes hash = 2;
    oneof content {
        Order order = 3;
        Reciept reciept = 4;
    }
}