syntax = "proto3";

option go_package = "./pb";

enum Operation {
    SET = 0;
    GET = 1;
    DELETE = 2;
}

message Txn {
    string key = 2;
    bytes value = 3;
}

message Order {
    int64 timestamp = 1;
    Operation operation = 2;
    repeated Txn txnList =3;
}

message RecieptItem{
    
    bool status = 1;
    string error = 2;
    string key = 3;
    optional bytes val = 4;
}

message Reciept { 
    int64 timestamp = 1;
    Operation operation = 2;
    repeated RecieptItem items = 3;
}

message msg {
    
    bytes uuid = 1;
    oneof content {
        Order order = 3;
        Reciept reciept = 4;
    }
}